# MonoDimFeatEdge (Object)

**_1-D boundary belonging to a feature whose topological result is one dimensional._**
**Role** : This [Boundary](../MecModInterfaces/interface_Boundary_14542.md) object may be, for example, in a part containing a Sketch which is made up of a circle arc and a spline, the circle arc. You will create a MonoDimFeatEdge object using the [Shapes.GetBoundary](../MecModInterfaces/interface_Shapes_8122.htm#GetBoundary) , [HybridShapes.GetBoundary](../MecModInterfaces/interface_HybridShapes_30836.htm#GetBoundary) , [Sketches.GetBoundary](../MecModInterfaces/interface_Sketches_14228.htm#GetBoundary) or [Selection.SelectElement2](../InfInterfaces/interface_Selection_18040.htm#SelectElement2) method. Then, you pass it to the operator (such as [HybridShapeFactory.AddNewPointTangent](../GSMInterfaces/interface_HybridShapeFactory_68680.htm#AddNewPointTangent) ). The lifetime of a MonoDimFeatEdge object is limited, see [Boundary](../MecModInterfaces/interface_Boundary_14542.md).